[2024-05-12T16:32:31.827+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:32:31.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:32:15.209132+00:00 [queued]>
[2024-05-12T16:32:31.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:32:15.209132+00:00 [queued]>
[2024-05-12T16:32:31.852+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:32:31.863+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:32:15.209132+00:00
[2024-05-12T16:32:31.869+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:32:31.870+0000] {standard_task_runner.py:63} INFO - Started process 744 to run task
[2024-05-12T16:32:31.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:32:15.209132+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpapl2j0ab']
[2024-05-12T16:32:31.872+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask dvc_add_and_push
[2024-05-12T16:32:31.910+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:32:15.209132+00:00 [running]> on host d64c2340cf7b
[2024-05-12T16:32:31.980+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:32:15.209132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:32:15.209132+00:00'
[2024-05-12T16:32:31.981+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:32:31.982+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:32:31.982+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd /opt/***/dags\ndvc init -f && dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:32:31.989+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:32:32.951+0000] {subprocess.py:93} INFO - ERROR: failed to initiate DVC - /opt/***/dags is not tracked by any supported SCM tool (e.g. Git). Use `--no-scm` if you don't want to use any SCM or `--subdir` if initializing inside a subdirectory of a parent SCM repository.
[2024-05-12T16:32:33.066+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-12T16:32:33.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:32:33.074+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-12T16:32:33.078+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=dvc_add_and_push, run_id=manual__2024-05-12T16:32:15.209132+00:00, execution_date=20240512T163215, start_date=20240512T163231, end_date=20240512T163233
[2024-05-12T16:32:33.092+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task dvc_add_and_push (Bash command failed. The command returned a non-zero exit code 1.; 744)
[2024-05-12T16:32:33.129+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T16:32:33.142+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:32:33.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
