[2024-05-12T16:13:28.752+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:13:28.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:12:37.739413+00:00 [queued]>
[2024-05-12T16:13:28.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:12:37.739413+00:00 [queued]>
[2024-05-12T16:13:28.779+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:13:28.794+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:12:37.739413+00:00
[2024-05-12T16:13:28.801+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:13:28.802+0000] {standard_task_runner.py:63} INFO - Started process 124 to run task
[2024-05-12T16:13:28.802+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:12:37.739413+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpmu8ln90l']
[2024-05-12T16:13:28.803+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask dvc_add_and_push
[2024-05-12T16:13:28.844+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:12:37.739413+00:00 [running]> on host d64c2340cf7b
[2024-05-12T16:13:28.909+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:12:37.739413+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:12:37.739413+00:00'
[2024-05-12T16:13:28.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:13:28.911+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:13:28.912+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ndvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:13:28.924+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:13:30.591+0000] {subprocess.py:93} INFO - Setting 'mygoogledrive' as a default remote.
[2024-05-12T16:13:30.592+0000] {subprocess.py:93} INFO - ERROR: configuration error - config file error: Not inside a DVC repo
[2024-05-12T16:13:31.314+0000] {subprocess.py:97} INFO - Command exited with return code 251
[2024-05-12T16:13:31.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:13:31.323+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 251.
[2024-05-12T16:13:31.439+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=dvc_add_and_push, run_id=manual__2024-05-12T16:12:37.739413+00:00, execution_date=20240512T161237, start_date=20240512T161328, end_date=20240512T161331
[2024-05-12T16:13:31.886+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task dvc_add_and_push (Bash command failed. The command returned a non-zero exit code 251.; 124)
[2024-05-12T16:13:31.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T16:13:31.960+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:13:33.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
