[2024-05-12T15:29:01.389+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T15:29:01.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T15:28:47.122272+00:00 [queued]>
[2024-05-12T15:29:01.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T15:28:47.122272+00:00 [queued]>
[2024-05-12T15:29:01.415+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T15:29:01.428+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 15:28:47.122272+00:00
[2024-05-12T15:29:01.434+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4250) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T15:29:01.435+0000] {standard_task_runner.py:63} INFO - Started process 4252 to run task
[2024-05-12T15:29:01.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T15:28:47.122272+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpdvgkp__s']
[2024-05-12T15:29:01.436+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask dvc_add_and_push
[2024-05-12T15:29:01.476+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T15:28:47.122272+00:00 [running]> on host 8b349270b58a
[2024-05-12T15:29:01.534+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T15:28:47.122272+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T15:28:47.122272+00:00'
[2024-05-12T15:29:01.536+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T15:29:01.537+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T15:29:01.538+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\npython3 -m dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && \\\npython3 -m dvc add extracted_data.csv && \\\ngit add . && \\\ngit commit -m "committed via ***" && \\\npython3 -m dvc push -r mygoogleDrive && \\\ngit push']
[2024-05-12T15:29:01.546+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T15:29:01.594+0000] {subprocess.py:93} INFO - /home/***/.local/bin/python3: No module named dvc
[2024-05-12T15:29:01.597+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-12T15:29:01.598+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T15:29:01.605+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-12T15:29:01.609+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=dvc_add_and_push, run_id=manual__2024-05-12T15:28:47.122272+00:00, execution_date=20240512T152847, start_date=20240512T152901, end_date=20240512T152901
[2024-05-12T15:29:01.620+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task dvc_add_and_push (Bash command failed. The command returned a non-zero exit code 1.; 4252)
[2024-05-12T15:29:01.649+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T15:29:01.663+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T15:29:01.666+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
