[2024-05-12T13:02:28.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T13:02:28.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops-dag.extract_articles manual__2024-05-12T13:02:26.437102+00:00 [queued]>
[2024-05-12T13:02:28.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops-dag.extract_articles manual__2024-05-12T13:02:26.437102+00:00 [queued]>
[2024-05-12T13:02:28.124+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T13:02:28.134+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_articles> on 2024-05-12 13:02:26.437102+00:00
[2024-05-12T13:02:28.138+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T13:02:28.140+0000] {standard_task_runner.py:63} INFO - Started process 2130 to run task
[2024-05-12T13:02:28.140+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops-dag', 'extract_articles', 'manual__2024-05-12T13:02:26.437102+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpy3hw4z47']
[2024-05-12T13:02:28.142+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask extract_articles
[2024-05-12T13:02:28.175+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops-dag.extract_articles manual__2024-05-12T13:02:26.437102+00:00 [running]> on host 8b349270b58a
[2024-05-12T13:02:28.241+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***-demo' AIRFLOW_CTX_DAG_ID='mlops-dag' AIRFLOW_CTX_TASK_ID='extract_articles' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T13:02:26.437102+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T13:02:26.437102+00:00'
[2024-05-12T13:02:28.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T13:02:28.244+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T13:02:28.245+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 21, in extract_articles
    response = requests.get(source)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 's': No scheme supplied. Perhaps you meant https://s?
[2024-05-12T13:02:28.255+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mlops-dag, task_id=extract_articles, run_id=manual__2024-05-12T13:02:26.437102+00:00, execution_date=20240512T130226, start_date=20240512T130228, end_date=20240512T130228
[2024-05-12T13:02:28.264+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task extract_articles (Invalid URL 's': No scheme supplied. Perhaps you meant https://s?; 2130)
[2024-05-12T13:02:28.313+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T13:02:28.330+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T13:02:28.333+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
