[2024-05-12T16:39:20.711+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:39:20.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:23.123236+00:00 [queued]>
[2024-05-12T16:39:20.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:23.123236+00:00 [queued]>
[2024-05-12T16:39:20.742+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:39:20.753+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:38:23.123236+00:00
[2024-05-12T16:39:20.758+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:39:20.759+0000] {standard_task_runner.py:63} INFO - Started process 119 to run task
[2024-05-12T16:39:20.759+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:38:23.123236+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpgesi3y82']
[2024-05-12T16:39:20.760+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask dvc_add_and_push
[2024-05-12T16:39:20.817+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:38:23.123236+00:00 [running]> on host e6e483b741f2
[2024-05-12T16:39:20.905+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:38:23.123236+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:38:23.123236+00:00'
[2024-05-12T16:39:20.907+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:39:20.909+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:39:20.910+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd /opt/***/dags\ndvc init -f --no-scm && dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:39:20.919+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:39:21.919+0000] {subprocess.py:93} INFO - Initialized DVC repository.
[2024-05-12T16:39:21.919+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:39:21.924+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:39:21.925+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:39:21.926+0000] {subprocess.py:93} INFO - |        DVC has enabled anonymous aggregate usage analytics.         |
[2024-05-12T16:39:21.926+0000] {subprocess.py:93} INFO - |     Read the analytics documentation (and how to opt-out) here:     |
[2024-05-12T16:39:21.927+0000] {subprocess.py:93} INFO - |             <https://dvc.org/doc/user-guide/analytics>              |
[2024-05-12T16:39:21.928+0000] {subprocess.py:93} INFO - |                                                                     |
[2024-05-12T16:39:21.928+0000] {subprocess.py:93} INFO - +---------------------------------------------------------------------+
[2024-05-12T16:39:21.929+0000] {subprocess.py:93} INFO - 
[2024-05-12T16:39:21.929+0000] {subprocess.py:93} INFO - What's next?
[2024-05-12T16:39:21.930+0000] {subprocess.py:93} INFO - ------------
[2024-05-12T16:39:21.931+0000] {subprocess.py:93} INFO - - Check out the documentation: <https://dvc.org/doc>
[2024-05-12T16:39:21.932+0000] {subprocess.py:93} INFO - - Get help and share ideas: <https://dvc.org/chat>
[2024-05-12T16:39:21.933+0000] {subprocess.py:93} INFO - - Star us on GitHub: <https://github.com/iterative/dvc>
[2024-05-12T16:39:22.928+0000] {subprocess.py:93} INFO - Setting 'mygoogledrive' as a default remote.
[2024-05-12T16:39:22.931+0000] {subprocess.py:93} INFO - ERROR: configuration error - config file error: remote 'mygoogledrive' already exists. Use `-f|--force` to overwrite it.
[2024-05-12T16:39:23.110+0000] {subprocess.py:97} INFO - Command exited with return code 251
[2024-05-12T16:39:23.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:39:23.121+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 251.
[2024-05-12T16:39:23.141+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=dvc_add_and_push, run_id=manual__2024-05-12T16:38:23.123236+00:00, execution_date=20240512T163823, start_date=20240512T163920, end_date=20240512T163923
[2024-05-12T16:39:23.156+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task dvc_add_and_push (Bash command failed. The command returned a non-zero exit code 251.; 119)
[2024-05-12T16:39:23.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T16:39:23.236+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:39:23.238+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
