[2024-05-12T16:31:36.488+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:31:36.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:31:19.830318+00:00 [queued]>
[2024-05-12T16:31:36.515+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:31:19.830318+00:00 [queued]>
[2024-05-12T16:31:36.516+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T16:31:36.529+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dvc_add_and_push> on 2024-05-12 16:31:19.830318+00:00
[2024-05-12T16:31:36.534+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=702) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T16:31:36.535+0000] {standard_task_runner.py:63} INFO - Started process 704 to run task
[2024-05-12T16:31:36.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'web_article_scraping', 'dvc_add_and_push', 'manual__2024-05-12T16:31:19.830318+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmpz1co475v']
[2024-05-12T16:31:36.536+0000] {standard_task_runner.py:91} INFO - Job 136: Subtask dvc_add_and_push
[2024-05-12T16:31:36.579+0000] {task_command.py:426} INFO - Running <TaskInstance: web_article_scraping.dvc_add_and_push manual__2024-05-12T16:31:19.830318+00:00 [running]> on host d64c2340cf7b
[2024-05-12T16:31:36.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_article_scraping' AIRFLOW_CTX_TASK_ID='dvc_add_and_push' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:31:19.830318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:31:19.830318+00:00'
[2024-05-12T16:31:36.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:31:36.645+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T16:31:36.646+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd /opt/***/dags\ndvc init --no-scm && dvc remote add -d mygoogleDrive gdrive://1akLltC_11ZTBzZF-D4cZt_sZIf-jheJE && dvc add extracted_data.csv && dvc push -r mygoogleDrive']
[2024-05-12T16:31:36.655+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T16:31:37.391+0000] {subprocess.py:93} INFO - ERROR: failed to initiate DVC - '.dvc' exists. Use `-f` to force.
[2024-05-12T16:31:37.524+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-12T16:31:37.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:31:37.532+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-12T16:31:37.536+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=web_article_scraping, task_id=dvc_add_and_push, run_id=manual__2024-05-12T16:31:19.830318+00:00, execution_date=20240512T163119, start_date=20240512T163136, end_date=20240512T163137
[2024-05-12T16:31:37.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 136 for task dvc_add_and_push (Bash command failed. The command returned a non-zero exit code 1.; 704)
[2024-05-12T16:31:37.592+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T16:31:37.604+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:31:37.606+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
