[2024-05-12T13:07:26.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T13:07:26.168+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops-dag.Task_1 manual__2024-05-12T13:07:24.842115+00:00 [queued]>
[2024-05-12T13:07:26.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops-dag.Task_1 manual__2024-05-12T13:07:24.842115+00:00 [queued]>
[2024-05-12T13:07:26.175+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T13:07:26.183+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Task_1> on 2024-05-12 13:07:24.842115+00:00
[2024-05-12T13:07:26.188+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-12T13:07:26.189+0000] {standard_task_runner.py:63} INFO - Started process 2205 to run task
[2024-05-12T13:07:26.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops-dag', 'Task_1', 'manual__2024-05-12T13:07:24.842115+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/mlops_dag.py', '--cfg-path', '/tmp/tmp5dai9qtw']
[2024-05-12T13:07:26.191+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask Task_1
[2024-05-12T13:07:26.222+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops-dag.Task_1 manual__2024-05-12T13:07:24.842115+00:00 [running]> on host 8b349270b58a
[2024-05-12T13:07:26.286+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***-demo' AIRFLOW_CTX_DAG_ID='mlops-dag' AIRFLOW_CTX_TASK_ID='Task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T13:07:24.842115+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T13:07:24.842115+00:00'
[2024-05-12T13:07:26.288+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T13:07:26.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T13:07:26.289+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mlops_dag.py", line 20, in extract
    response = requests.get(source)
                            ^^^^^^
NameError: name 'source' is not defined. Did you mean: 'sources'?
[2024-05-12T13:07:26.298+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mlops-dag, task_id=Task_1, run_id=manual__2024-05-12T13:07:24.842115+00:00, execution_date=20240512T130724, start_date=20240512T130726, end_date=20240512T130726
[2024-05-12T13:07:26.306+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task Task_1 (name 'source' is not defined; 2205)
[2024-05-12T13:07:26.323+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T13:07:26.343+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T13:07:26.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
